package com.ernielee.storyideas3;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.Random;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ArrayList<String> characters = new ArrayList();
        ArrayList<String> objects = new ArrayList();
        ArrayList<String> events = new ArrayList();

        populateLists(characters, objects, events);

        TextView character = findViewById(R.id.tv_character);
        TextView object = findViewById(R.id.tv_object);
        TextView event = findViewById(R.id.tv_event);
        Button next = findViewById(R.id.btn_next);

        next.setOnClickListener(v -> {
            Random r = new Random();

            int r_c = r.nextInt(characters.size());
            int r_o = r.nextInt(objects.size());
            int r_e = r.nextInt(events.size());

            String c = characters.get(r_c);
            String o = objects.get(r_o);
            String e = events.get(r_e) + ".";

            character.setText(c);
            object.setText(o);
            event.setText(e);
        });
    }

    public void populateLists(ArrayList<String> c, ArrayList<String> o, ArrayList<String> e) {
        c.add("an ex-superhero");
        o.add("an alarm clock");
        e.add("the apocalypse");
        c.add("a mouse");
        o.add("a mountain");
        e.add("a character falls from a great height");
        c.add("a student");
        o.add("a watch");
        e.add("a character near a pier sees a shark");
        c.add("a red-haired person");
        o.add("a screen");
        e.add("a car won't start");
        c.add("a person who will only eat cheese and crackers");
        o.add("healthy snacks");
        e.add("a character finds a hidden path");
        c.add("a ghost");
        o.add("baking tray");
        e.add("a party");
        c.add("a cowboy");
        o.add("a beehive");
        e.add("the election of a political candidate");
        c.add("a person with a limp");
        o.add("a teapot");
        e.add("a camping trip");
        c.add("a person who wants to be a dentist");
        o.add("earplugs");
        e.add("a person changes their religious beliefs");
        c.add("a person who has a pet");
        o.add("tape");
        e.add("a person goes to a hospital for a fake medical condition");
        c.add("a person who has a severe health problem");
        o.add("a hotel");
        e.add("a person is suspected of committing a crime");
        c.add("a person who gets taunted often");
        o.add("a quilt");
        e.add("somebody wins a lottery");
        c.add("a person starting a new career");
        o.add("a spoon");
        e.add("a storm");
        c.add("a person with a blue item of clothing");
        o.add("a rocket");
        e.add("a character has to make a tough decision");
        c.add("a person who is barefoot most of the time");
        o.add("a camera");
        e.add("a major sporting event takes place");
        c.add("a person with facial hair");
        o.add("a peephole");
        e.add("something important is managed by an untrustworthy person");
        c.add("a parent who misses their child");
        o.add("a stroller made for pets");
        e.add("a game competition");
        c.add("a person struggling with addiction");
        o.add("a town square");
        e.add("a romance between unlikely people");
        c.add("a person with an emotional or mental health disorder");
        o.add("a list");
        e.add("the residents of a city are locked down to protect them");
        c.add("a member of a royal family");
        o.add("food colouring");
        e.add("a character consumes poison");
        c.add("a child of an infamous person");
        o.add("a remote control");
        e.add("a person wins an award for bravery");
        c.add("an evil wizard");
        o.add("a train");
        e.add("a group of friends have a disagreement in a car");
        c.add("a person who likes to play golf");
        o.add("a multi-tool");
        e.add("a clone");
        c.add("an army of monkeys");
        o.add("a drink");
        e.add("a character is avoiding prison after committing a horrible crime");
        c.add("a horse");
        o.add("a coat");
        e.add("a tea party");
        c.add("a person with a tattoo");
        o.add("a banana");
        e.add("a volcanic eruption");
        c.add("a nuclear scientist");
        o.add("a feather");
        e.add("a failed assassination attempt");
        c.add("a person seeking revenge");
        o.add("a casino");
        e.add("a devastating attack of a town");
        c.add("a decorated officer");
        o.add("a supercomputer");
        e.add("an eating contest");
        c.add("a person complaining of a medical problem that nobody believes");
        o.add("a compass");
        e.add("a person seeks to seclude itself from the rest of the world");
        c.add("a people-pleaser");
        o.add("a room without windows");
        e.add("a character gets lost");
        c.add("a bitter loner");
        o.add("a roof");
        e.add("a lab accident");
        c.add("a single parent");
        o.add("an indoor plant");
        e.add("a rivalry between 2 characters causes problems for a 3rd character");
        c.add("a prankster");
        o.add("a knife");
        e.add("a government shutdown");
        c.add("a person who is ashamed of something");
        o.add("a musical instrument");
        e.add("a tomb robbery in an ancient pyramid");
        c.add("a person with a secret");
        o.add("a famous painting");
        e.add("a character bakes break for local guards");
        c.add("a person with a secret admirer");
        o.add("a bear suit");
        e.add("a trip around the world");
        c.add("a homeless person");
        o.add("a hose");
        e.add("a character gets an unexpected opportunity");
        c.add("an aggressive person");
        o.add("a family heirloom");
        e.add("a storm");
        c.add("a workaholic");
        o.add("a large vehicle");
        e.add("backstage during a ballet while the dancers are hostile");
        c.add("a person with a minor medical condition");
        o.add("a package");
        e.add("a burglary");
        c.add("a thief");
        o.add("scissors");
        e.add("a character gets ahold of information from a spy");
        c.add("a person who is lying");
        o.add("a cellar");
        e.add("a natural disaster");
        c.add("a cruel person");
        o.add("a bookcase");
        e.add("a character who is low-ranking becomes the most powerful person");
        c.add("a reluctant person");
        o.add("a shop");
        e.add("a young person who needs to grow up quickly");
        c.add("a person who believes their life is in ruins");
        o.add("a menu");
        e.add("an island is discovered");
        c.add("a generous person");
        o.add("hydrant");
        e.add("a character returns after having been missing for a long time");
        c.add("an explorer");
        o.add("a train station");
        e.add("a siege in a castle");
        c.add("an unlikely ally");
        o.add("a ladybug");
        e.add("a study group gets interrupted");
        c.add("an expert in tying knots");
        o.add("a recently invented machine");
        e.add("a character is trying to avoid a situation that is inevitable");
        c.add("a weightlifter");
        o.add("a sword");
        e.add("a refrigerator quit working");
        c.add("a person who has an odd collection");
        o.add("a door that gets stuck");
        e.add("a fire is started to cover evidence");
        c.add("a detective");
        o.add("a micro controller");
        e.add("a microwave explodes");
        c.add("a person who is almost always wearing a hat");
        o.add("a laptop");
        e.add("the power cuts out just before the resolution ");
        c.add("a person who complains about everything, no matter how good");
        o.add("a game console");
        e.add("a character sleepwalks off a balcony");
        c.add("a person who is vegetarian or vegan");
        o.add("a tool set");
        e.add("a washing machine is filled unevenly so it hops around during the spin cycle and the hose gets disconnected");
        c.add("a person with a severe allergy");
        o.add("dirty dishes");
        e.add("a vehicle accident occurs and the police have a difficult time with one of the characters");
        c.add("a person with a mild allergy");
        o.add("a noisy appliance");
        e.add("an item other than a weapon is used as if it is a weapon");
        c.add("a person who likes physical contact");
        o.add("a broken shelf");
        e.add("a person goes to a doctor for a problem the doctor won't acknowledge");
        c.add("an ex-professional sports player");
        o.add("a trash can that best fits only a rare size trash bag");
        e.add("a radio DJ, on their last day, plays every version of only 1 song for their entire shift");
        c.add("a lifelong student");
        o.add("a light that flickers but won't turn off");
        e.add("a deck or balcony collapses");
        c.add("a person who is technically a parent");
        o.add("a dripping faucet");
        e.add("a character wins the lottery");
        c.add("a person who thinks they are good at teaching");
        o.add("a heating pad or blanket");
        e.add("a hated person is in charge");
        c.add("a relative of the narrator");
        o.add("a fanny pack");
        e.add("a person makes a threat against another person");
        c.add("an embezzler");
        o.add("a filter");
        e.add("a box mysteriously shows up at a character's door");
        c.add("a person whose beliefs are scorned by many around them");
        o.add("water with foam on top");
        e.add("a character is alone during a historically social holiday");
        c.add("a person with ");
        o.add("pipes");
        e.add("a city has a major health crisis due to a form of pollution");
        c.add("an investigative journalist");
        o.add("a wheely bin or trash can with wheels");
        e.add("a major metropolitan area has no running water");
        c.add("a person who wants to be a parent");
        o.add("an aquifer");
        e.add("a neighbour threatens a character after they've had a massive disagreement");
        c.add("a person who has a fear of something they must interact with for survival");
        o.add("an old medal");
        e.add("a character finds something buried underground ");
        c.add("a person who has an assistive device they refuse to use");
        o.add("a stool");
        e.add("a character trips and bruises their knee");
        c.add("a parent who feels like they need to protect their child");
        o.add("a crate");
        e.add("a character is questioning their beliefs");
        c.add("a medical professional");
        o.add("a tube");
        e.add("a character is struggling to learn to read");
        c.add("a character impersonates a doctor");
        o.add("a hinge");
        e.add("a character fails to be supportive to someone they care about");
        c.add("a person with a unique name");
        o.add("a cooler");
        e.add("an honorary dinner");
        c.add("a scientist");
        o.add("a soda");
        e.add("a large family meal");
        c.add("a person with pica");
        o.add("a noose");
        e.add("a fight between 2 characters who can't prove who is right");
        c.add("a person who uses fancy words enough to annoy everybody around them");
        o.add("a fireplace");
        e.add("a world where every country has a form of universal basic income");
        c.add("a campaign manager");
        o.add("a coat rack");
        e.add("a global pandemic");
        c.add("a global corporation");
        o.add("a log");
        e.add("a flock of birds causes damage that affects the main character");
        c.add("an investor close to bankruptcy");
        o.add("a hammer");
        e.add("a main character gets injured to the point they question their ability to continue with their career");
        c.add("a person who often lies to themself about who they are");
        o.add("a substance that has caught on as a type of food but has major health consequences after a certain amount is consumed");
        e.add("a choir gets interrupted by hecklers");
        c.add("an inventor");
        o.add("a complicated electronic device that doesn't come with a manual");
        e.add("a city's largest employer shuts operations in that city");
        c.add("a person who spends most of their time doing volunteer work");
        o.add("a container that is extremely difficult to open");
        e.add("a person is in a crisis but has no way to get a professional or expert to help");
        c.add("a person who writes books and gives speeches for motivation and self-help");
        o.add("a book that is old and falling apart");
        e.add("a major national economic crisis with a leader who doesn't know how to handle it");
        c.add("a person who follows rules far beyond what they were meant for");
        o.add("a street sign pointing the wrong direction");
        e.add("a radio picks up an inexplicable signal");
        c.add("a spoiled brat");
        o.add("a machine that controls weather or seasons");
        e.add("a character is put in a role in an organization or government that they don't know how to do");
        c.add("a person who wears clothes inappropriate for the situation");
        o.add("an electric tool that works intermittently");
        e.add("a character must make a choice that will affect those they care about");
        c.add("a person who believes they are an expert in a certain period in history");
        o.add("2 speaking robots, 1 that sounds robotic and 1 that sounds human");
        e.add("a major technical innovation");
        c.add("a composer who comes up with their own notation that nobody else understands");
        o.add("a fuel cell battery");
        e.add("2 warring neighbouring countries have a truce");
        c.add("a conspirator");
        o.add("a chair in disrepair");
        e.add("a minor character engages in embezzlement");
        c.add("a person using a name other than their own");
        o.add("a wave");
        e.add("a seminar that leaves people believing something that isn't true");
        c.add("a philosopher");
        o.add("a treehouse");
        e.add("a potential collision on a sidewalk between a lawnmower and a pair of runners");
        c.add("a person who talks as if they care but have very little real understanding of the problem");
        o.add("a cave");
        e.add("a roof gets a leak");
        c.add("a person of extremely high or low intelligence");
        o.add("a damaged new bucket");
        e.add("an expensive item falls to the floor");
        c.add("a monk");
        o.add("a cage");
        e.add("a character pricks their finger on a cactus");
        c.add("a disgraced emperor");
        o.add("a harness");
        e.add("a character gains renown for coming up with a unique way of doing something most people do daily");
        c.add("a person who uses coercion on a public official of great power");
        o.add("a vest");
        e.add("a character moves to a new area only to find they can't afford the taxes");
        c.add("an entertainer");
        o.add("an off-road vehicle");
        e.add("production is stopped for a product in wide usage which causes anger in the citizens");
        c.add("a person with an accent that gets made fun of");
        o.add("a bow");
        e.add("a tree falls on a building");
        /*
        c.add("");
        o.add("");
        e.add("");
         */
    }
}